version: "2"

networks:
  swarm-network:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/16
          ip_range: 10.10.2.0/24

volumes:
  transcoding:
    driver: local

services:
  apache:
    image: httpd
    networks: 
      - swarm-network
    ports:
      - "80:80"
    restart: always
    environment:
      - affinity:container!=apache*

  # sudo docker-compose -H :4000 scale apache=2
  # sudo docker-compose -H :4000 ps
